[gmail]
display-name = "Emonadeo"
downloads-dir = "~/Downloads"
signature = ""
email-listing-page-size = 32

default = true
email = "emonadeo@gmail.com"

backend = "imap"
imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "emonadeo@gmail.com"
imap-auth = "oauth2"
imap-oauth2-client-id = "669261423442-nfgbrtk2h704bdksbd0nk0rnd5vffd7r.apps.googleusercontent.com"
imap-oauth2-auth-url = "https://accounts.google.com/o/oauth2/v2/auth"
imap-oauth2-token-url = "https://www.googleapis.com/oauth2/v3/token"
imap-oauth2-pkce = true
imap-oauth2-scope = "https://mail.google.com/"

sender = "smtp"
smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "emonadeo@gmail.com"
smtp-auth = "oauth2"
smtp-oauth2-client-id = "669261423442-nfgbrtk2h704bdksbd0nk0rnd5vffd7r.apps.googleusercontent.com"
smtp-oauth2-client-secret = { keyring = "gmail-imap-oauth2-client-secret" }
smtp-oauth2-access-token = { keyring = "gmail-imap-oauth2-access-token" }
smtp-oauth2-refresh-token = { keyring = "gmail-imap-oauth2-refresh-token" }
smtp-oauth2-auth-url = "https://accounts.google.com/o/oauth2/v2/auth"
smtp-oauth2-token-url = "https://www.googleapis.com/oauth2/v3/token"
smtp-oauth2-pkce = true
smtp-oauth2-scope = "https://mail.google.com/"

[gmail.folder-aliases]
inbox = "INBOX"
sent = "[Gmail]/Sent Mail"
drafts = "[Gmail]/Drafts"
trash = "[Gmail]/Trash"
