frame = "buttonless"
title-hidden = true
fork = true
tabs = false

[font]
normal = ["GeistMono Nerd Font"]
size = 16

[font.features]
"Geist Mono" = ["-liga", "-calt", "-clig"]
"GeistMono Nerd Font" = ["-liga", "-calt", "-clig"]
"GeistMono Nerd Font Mono" = ["-liga", "-calt", "-clig"]
"GeistMono Nerd Font Propo" = ["-liga", "-calt", "-clig"]
"JetBrains Mono" = ["-liga", "-calt", "-clig"]
"JetBrains Mono Nerd Font" = ["-liga", "-calt", "-clig"]
"JetBrains Mono Nerd Font Mono" = ["-liga", "-calt", "-clig"]
"JetBrains Mono Nerd Font Propo" = ["-liga", "-calt", "-clig"]
"Maple Mono" = ["-liga", "-calt", "-clig", "+cv01", "+cv03"]
