"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:red)\
$directory\
[ ](fg:red bg:yellow)\
$git_branch\
[│](fg:base bg:yellow)\
$git_status\
[ ](fg:yellow bg:blue)\
$c\
$dart\
$deno\
$elixir\
$golang\
$haskell\
$java\
$kotlin\
$lua\
$nodejs\
$ocaml\
$php\
$python\
$rust\
$zig\
[](fg:blue)\
$line_break$character\
"""

# palettes

palette = "catppuccin"

[palettes.catppuccin]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[line_break]
disabled = false

[character]
disabled = false
format = '$symbol'
success_symbol = '[↳](bold fg:green)'
error_symbol = '[↳](bold fg:red)'
vimcmd_symbol = '[↳](bold fg:blue)'
vimcmd_replace_one_symbol = '[↳](bold fg:purple)'
vimcmd_replace_symbol = '[↳](bold fg:purple)'
vimcmd_visual_symbol = '[↳](bold fg:yellow)'

# disabled modules
[time]
disabled = true

# 1: directory

[directory]
read_only = "󰌾"
style = "bg:red fg:base"
format = "[$path ]($style)"

[directory.substitutions]
"Desktop" = ""
"Documents" = "󰈙"
"Downloads" = ""
"Games" = ""
"Music" = "󰝚"
"Movies" = ""
"Pictures" = ""
"Development" = "󰲋"

# 2: git

[git_branch]
symbol = ""
style = "fg:base bg:yellow"
format = "[$symbol $branch(:$remote_branch)]($style)"

[git_status]
style = "fg:base bg:yellow"
format = "[$all_status$ahead_behind ]($style)"

# 3: language/runtime

[c]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[dart]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[deno]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[elixir]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[golang]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[haskell]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[java]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[kotlin]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[lua]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[nodejs]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[ocaml]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[php]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[python]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[rust]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

[zig]
symbol = ""
style = "fg:base bg:blue"
format = '[$symbol $version ]($style)'

