[font]
normal = ["Departure Mono"]
size = 13.5

[font.features]
"Departure Mono" = ["-liga", "-calt", "-clig", "-dlig"]
"Geist Mono" = ["-liga", "-calt", "-clig", "-dlig"]
"GeistMono Nerd Font" = ["-liga", "-calt", "-clig", "-dlig"]
"GeistMono Nerd Font Mono" = ["-liga", "-calt", "-clig", "-dlig"]
"GeistMono Nerd Font Propo" = ["-liga", "-calt", "-clig", "-dlig"]
"JetBrains Mono" = ["-liga", "-calt", "-clig", "-dlig"]
"JetBrains Mono Nerd Font" = ["-liga", "-calt", "-clig", "-dlig"]
"JetBrains Mono Nerd Font Mono" = ["-liga", "-calt", "-clig"]
"JetBrains Mono Nerd Font Propo" = ["-liga", "-calt", "-clig", "-dlig"]
"Maple Mono" = ["-liga", "-calt", "-clig", "-dlig", "+cv01", "+cv03"]
